# DNS防泄露版本
# 必读！！！
# 注意规则在满足自己需求情况下，尽量做到精简，不要过度复杂，以免影响性能。
# 跑裸核用户请自行去掉下方控制面板模块的注释。
# 机场订阅
proxy-providers:
  Airport1:
    url: "机场订阅"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: 🐉 全球直连

# 节点信息
proxies:
  - {name: 🐉 全球直连, type: direct}

# 全局配置 
mixed-port: 7890
allow-lan: true
bind-address: "*"
ipv6: true
unified-delay: true
tcp-concurrent: true
log-level: warning
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true

# 为防止使用插件朋友遇到面板问题，我注释掉了此模块。
#external-controller: 0.0.0.0:9090
#secret: ""
#external-ui: ui
#external-ui-name: zashboard
#external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"

# 嗅探（fakeip下其实可以不用嗅探）
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

# 入站
tun:
  enable: true
  # system/gvisor/mixed
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  #使用nikki，混入全部不修改的情况，开启接口指定为nikki
  #device: nikki
  #使用仅内核自行修改下面三项为true
  auto-route: false
  auto-redirect: false
  auto-detect-interface: false

# DNS模块
dns:
  enable: true
  cache-algorithm: arc
  listen: 0.0.0.0:1053
  ipv6: true
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-range6: fdfe:dcba:9876::1/64
  fake-ip-filter-mode: blacklist
  nameserver:
    - 192.168.50.7:5553
  fake-ip-filter:
    - "rule-set:fakeipfilter_domain"
 
# 出站策略，根据自己情况调整每个策略里分组排序，增删都可以，比如把美国自动放到第一个，比如删除香港故转，注意别漏掉表情逗号等。
# 如果相应分组没有筛选到对应的国家，请根据自己节点名字调整筛选关键字。
# 没有再使用锚点，是考虑很多新手修改难度，这样新手修改某个分组更容易些。
proxy-groups:
  - {name: 🌐 默认节点, type: select, proxies: [🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🪄 手动选择, 🐉 全球直连]}
  - {name: 🪄 手动选择, type: select, include-all: true}
  - {name: ♻️ 自动选择, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "^((?!(🐉 全球直连)).)*$"}
  - {name: 📱 Telegram, type: select, proxies: [🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: 📳 即时通讯, type: select, proxies: [🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: 👨‍👩‍👧‍👦 社交媒体, type: select, proxies: [🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: 👨🏿‍💻 GitHub, type: select, proxies: [🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: 🤖 ChatGPT, type: select, proxies: [🇸🇬 新加坡节点, 🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: 🤖 Copilot, type: select, proxies: [🇸🇬 新加坡节点, 🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: 🤖 Gemini, type: select, proxies: [🇸🇬 新加坡节点, 🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: 🤖 AI服务, type: select, proxies: [🇺🇲 美国节点,🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点,  🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: 🎶 TikTok, type: select, proxies: [🪄 手动选择, 🌐 默认节点, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: ▶️ YouTube, type: select, proxies: [🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: 🎥 Netflix, type: select, proxies: [🪄 手动选择, 🌐 默认节点, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: 🎥 DisneyPlus, type: select, proxies: [🪄 手动选择, 🌐 默认节点, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: 🎥 HBO, type: select, proxies: [🪄 手动选择, 🌐 默认节点, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: 🎥 PrimeVideo, type: select, proxies: [🪄 手动选择, 🌐 默认节点, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: 🎥 AppleTV+, type: select, proxies: [🪄 手动选择, 🌐 默认节点, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: 🎥 Emby, type: select, proxies: [🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: 🎧 Spotify, type: select, proxies: [🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: 📺 Bahamut, type: select, proxies: [🇼🇸 台湾节点, 🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: 🌎 国外媒体, type: select, proxies: [🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: 🛒 国外电商, type: select, proxies: [🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: 📢 谷歌FCM, type: select, proxies: [🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: 🔎 谷歌服务, type: select, proxies: [🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: 🍏 苹果服务, type: select, proxies: [🐉 全球直连, 🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点]}
  - {name: ☁️ OneDrive, type: select, proxies: [🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: Ⓜ️ 微软服务, type: select, proxies: [🐉 全球直连, 🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点]}
  - {name: 🎮 Steam, type: select, proxies: [🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: 🎮 游戏平台, type: select, proxies: [🐉 全球直连, 🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点]}
  - {name: 🛜 测速工具, type: select, proxies: [🐉 全球直连, 🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点]}
  - {name: 🗃️ PayPal, type: select, proxies: [🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: 🏡 自定义直连, type: select, proxies: [🐉 全球直连, 🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点]}
  - {name: 🐟 漏网之鱼, type: select, proxies: [🌐 默认节点, 🪄 手动选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇼🇸 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🐉 全球直连]}
  - {name: 🇭🇰 香港节点, type: select, include-all: true, filter: '(🇭🇰|港|HK|Hong\s?Kong|hongkong|HONG\s?KONG|HKG|深港|九龙|Kowloon|新界|沙田|荃湾|葵涌)'}
  - {name: 🇼🇸 台湾节点, type: select, include-all: true, filter: '(🇹🇼|🇼🇸|台|新北|彰化|Taiwan|TAIWAN|TWN|TPE|ROC)'}
  - {name: 🇸🇬 新加坡节点, type: select, include-all: true, filter: '(🇸🇬|新加坡|坡|狮城|Singapore|SINGAPORE|SIN)'}
  - {name: 🇯🇵 日本节点, type: select, include-all: true, filter: '(🇯🇵|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|Japan|JAPAN|JPN|NRT|HND|KIX|TYO|OSA|关西|Kansai|KANSAI)'}
  - {name: 🇰🇷 韩国节点, type: select, include-all: true, filter: '(🇰🇷|Korea|KOREA|KOR|首尔|韩|韓|春川|Chuncheon|ICN)'}
  - {name: 🇺🇲 美国节点, type: select, include-all: true, filter: '(🇺🇸|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|纽约|纽纽|亚特兰大|迈阿密|华盛顿|United States|UnitedStates|UNITED STATES|USA|America|AMERICA|JFK|EWR|IAD|ATL|ORD|MIA|NYC|LAX|SFO|SEA|DFW|SJC)'}
  - {name: 🇨🇦 加拿大节点, type: select, include-all: true, filter: '(🇨🇦|加拿大|Canada|CANADA|CAN|渥太华|温哥华|卡尔加里|蒙特利尔|Montreal|YVR|YYZ|YUL)'}
  - {name: 🇬🇧 英国节点, type: select, include-all: true, filter: '(🇬🇧|英国|Britain|United Kingdom|UNITED KINGDOM|England|伦敦|曼彻斯特|Manchester|GBR|LHR|MAN)'}


# 规则匹配
rules:
  - RULE-SET,geoip-private,🐉 全球直连,no-resolve
  - RULE-SET,geosite-private,🐉 全球直连
  - RULE-SET,proxylite,🌐 默认节点
  - RULE-SET,custom_direct,🐉 全球直连
  - RULE-SET,geosite-google-cn,🐉 全球直连
  - RULE-SET,geosite-category-games@cn,🐉 全球直连
  - RULE-SET,geosite-steam@cn,🐉 全球直连
  - RULE-SET,geosite-steam,🎮 Steam
  - RULE-SET,geosite-category-game-platforms-download,🐉 全球直连
  - RULE-SET,geosite-category-public-tracker,🐉 全球直连
  - RULE-SET,geoip-telegram,📱 Telegram,no-resolve
  - RULE-SET,geosite-telegram,📱 Telegram
  - RULE-SET,geosite-category-communication,📳 即时通讯
  - RULE-SET,geosite-category-social-media-!cn,👨‍👩‍👧‍👦 社交媒体
  - RULE-SET,geosite-openai,🤖 ChatGPT
  - RULE-SET,geosite-bing,🤖 Copilot
  - RULE-SET,geosite-google-gemini,🤖 Gemini
  - RULE-SET,geosite-category-ai-!cn,🤖 AI服务
  - RULE-SET,geosite-github,👨🏿‍💻 GitHub
  - RULE-SET,geosite-ookla-speedtest,🛜 测速工具
  - RULE-SET,geosite-youtube,▶️ YouTube
  - RULE-SET,geosite-apple-tvplus,🎥 AppleTV+
  - RULE-SET,geosite-apple,🍏 苹果服务
  - RULE-SET,geoip-apple,🍏 苹果服务,no-resolve
  - RULE-SET,geosite-googlefcm,📢 谷歌FCM
  - RULE-SET,geoip-google,🔎 谷歌服务,no-resolve
  - RULE-SET,geosite-google,🔎 谷歌服务
  - RULE-SET,geosite-onedrive,☁️ OneDrive
  - RULE-SET,geosite-microsoft,Ⓜ️ 微软服务
  - RULE-SET,geosite-tiktok,🎶 TikTok
  - RULE-SET,geoip-netflix,🎥 Netflix,no-resolve
  - RULE-SET,geosite-netflix,🎥 Netflix
  - RULE-SET,geosite-disney,🎥 DisneyPlus
  - RULE-SET,geosite-hbo,🎥 HBO
  - RULE-SET,geosite-primevideo,🎥 PrimeVideo
  - RULE-SET,geosite-category-emby,🎥 Emby
  - RULE-SET,geosite-spotify,🎧 Spotify
  - RULE-SET,geosite-bahamut,📺 Bahamut
  - RULE-SET,geosite-category-games,🎮 游戏平台
  - RULE-SET,geosite-category-entertainment,🌎 国外媒体
  - RULE-SET,geosite-category-ecommerce,🛒 国外电商
  - RULE-SET,geosite-paypal,🗃️ PayPal
  - RULE-SET,geosite-geolocation-!cn,🌐 默认节点
  - RULE-SET,geosite-cn,🐉 全球直连
  - RULE-SET,geoip-cn,🐉 全球直连
  - MATCH,🐟 漏网之鱼

# 规则集
## type：可选http/file/inline  behavior：可选domain/ipcidr/classical format：可选yaml/text/mrs
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
rule-providers: 
  fakeipfilter_domain: {<<: *domain, url: "https://raw.githubusercontent.com/wwqgtxx/clash-rules/release/fakeip-filter.mrs"}
  geosite-private: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  custom_direct: { <<: *class, url: "https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/Custom_Direct.list"}
  proxylite: { <<: *class, url: "https://raw.githubusercontent.com/qichiyuhub/rule/main/proxy.list"}
  geosite-google-cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google-cn.mrs"}
  geosite-category-games@cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games@cn.mrs"}
  geosite-steam@cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam@cn.mrs"}
  geosite-steam: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.mrs"}
  geosite-category-game-platforms-download: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-game-platforms-download.mrs"}
  geosite-category-public-tracker: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-public-tracker.mrs" }
  geosite-telegram: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs" }
  geosite-category-communication: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-communication.mrs" }
  geosite-category-social-media-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-social-media-!cn.mrs" }
  geosite-openai: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/openai.mrs" }
  geosite-bing: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bing.mrs" }
  geosite-google-gemini: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google-gemini.mrs" }
  geosite-category-ai-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs" }
  geosite-github: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
  geosite-youtube: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
  geosite-apple-tvplus: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-tvplus.mrs"}
  geosite-apple: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs"}
  geosite-onedrive: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs"}
  geosite-microsoft: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  geosite-googlefcm: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/googlefcm.mrs"}
  geosite-google: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  geosite-tiktok: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"}
  geosite-netflix: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}
  geosite-disney: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/disney.mrs"}
  geosite-hbo: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/hbo.mrs"}
  geosite-primevideo: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/primevideo.mrs"}
  geosite-category-emby: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-emby.mrs"}
  geosite-spotify: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.mrs"}
  geosite-bahamut: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bahamut.mrs"}
  geosite-category-games: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games.mrs"}
  geosite-category-entertainment: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-entertainment.mrs"}
  geosite-category-ecommerce: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ecommerce.mrs"}
  geosite-paypal: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
  geosite-ookla-speedtest: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs"}
  geosite-geolocation-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  geosite-cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
  
  geoip-private: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"}
  geoip-cn: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  geoip-google: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  geoip-telegram: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  geoip-netflix: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}
  geoip-apple: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs"}

