proxy-providers:
  Airport1:
    url: "订阅链接"
    输入: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: DIRECT

port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
allow-lan: true
bind-address: "*"
ipv6: true
mode: rule
unified-delay: true
tcp-concurrent: true
log-level: warning
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true

external-controller: 0.0.0.0:9090
secret: ""
external-ui: ui
external-ui-name: zashboard
external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"

sniffer:
  enable: true
  override-destination: true
  sniff:
    QUIC:
      ports: [443, 8443]
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
  force-domain:
  - "+.netflix.com"
  - "+.nflxvideo.net"
  - "+.amazonaws.com"
  - "+.media.dssott.com"
  skip-domain:
  - Mijia Cloud
  - dlg.io.mi.com
  - "+.oray.com"
  - "+.sunlogin.net"
  - "+.push.apple.com"
  parse-pure-ip: true

tun:
  enable: true  #system/gvisor/mixed
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  auto-route: true
  auto-redirect: false
  auto-detect-interface: true

dns:
  enable: true
  cache-algorithm: arc
  listen: 0.0.0.0:7874
  ipv6: true
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-range6: fdfe:dcba:9876::1/64
  fake-ip-filter-mode: blacklist
  #default-nameserver:
    #- https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - 192.168.50.7:5553
    #- https://dns.alidns.com/dns-query
    #- https://doh.pub/dns-query
  #direct-nameserver:
    #- https://dns.alidns.com/dns-query
    #- https://doh.pub/dns-query
  nameserver:
    - 192.168.50.7:5553
    #- https://8.8.8.8/dns-query#RULES&ecs=223.5.5.0/24
  fake-ip-filter:
    - "rule-set:fakeip-filter"
    - "rule-set:domain-cn"

proxy-groups:
  - {name: 默认代理, type: select, proxies: [香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 手动选择, 自动选择, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-clashmeta.png}
  - {name: 自动选择, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "^((?!(官网|到期时间|剩余|流量|套餐|免费|订阅|GB|Expire Date|Traffic|ExpireDate)).)*$", icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-auto-select.png}
  - {name: 手动选择, type: select, include-all: true, filter: "^((?!(官网|到期时间|剩余|流量|套餐|免费|订阅|GB|Expire Date|Traffic|ExpireDate)).)*$", icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-select.png}
  - {name: Telegram, type: select, proxies: [默认代理, 手动选择, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-telegram.png}
  - {name: 即时通讯, type: select, proxies: [默认代理, 手动选择, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-messaging.png}
  - {name: 社交媒体, type: select, proxies: [默认代理, 手动选择, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-social-media.png}
  - {name: GitHub, type: select, proxies: [默认代理, 手动选择, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-github.png}
  - {name: ChatGPT, type: select, proxies: [新加坡节点, 默认代理, 手动选择, 自动选择, 香港节点, 台湾节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-chatgpt.png}
  - {name: Copilot, type: select, proxies: [新加坡节点, 默认代理, 手动选择, 自动选择, 香港节点, 台湾节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-copilot.png}
  - {name: Gemini, type: select, proxies: [新加坡节点, 默认代理, 手动选择, 自动选择, 香港节点, 台湾节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-gemini.png}
  - {name: AI服务, type: select, proxies: [美国节点,默认代理, 手动选择, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点,  加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-ai.png}
  - {name: TikTok, type: select, proxies: [手动选择, 默认代理, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-tiktok.png}
  - {name: YouTube, type: select, proxies: [默认代理, 手动选择, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-youtube.png}
  - {name: Netflix, type: select, proxies: [手动选择, 默认代理, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-netflix.png}
  - {name: DisneyPlus, type: select, proxies: [手动选择, 默认代理, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-disneyplus.png}
  - {name: HBO, type: select, proxies: [手动选择, 默认代理, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-hbo.png}
  - {name: PrimeVideo, type: select, proxies: [手动选择, 默认代理, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-primevideo.png}
  - {name: AppleTV+, type: select, proxies: [手动选择, 默认代理, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-appletv+.png}
  - {name: Emby, type: select, proxies: [默认代理, 手动选择, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-emby.png}
  - {name: Spotify, type: select, proxies: [默认代理, 手动选择, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-spotify.png}
  - {name: Bahamut, type: select, proxies: [台湾节点, 默认代理, 手动选择, 自动选择, 香港节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-bahamut.png}
  - {name: 国外媒体, type: select, proxies: [默认代理, 手动选择, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-entertainment.png}
  - {name: 国外电商, type: select, proxies: [默认代理, 手动选择, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-e-commerce.png}
  - {name: 谷歌FCM, type: select, proxies: [默认代理, 手动选择, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-notifications.png}
  - {name: 谷歌服务, type: select, proxies: [默认代理, 手动选择, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-google.png}
  - {name: 苹果服务, type: select, proxies: [全球直连, 默认代理, 手动选择, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-apple.png}
  - {name: OneDrive, type: select, proxies: [默认代理, 手动选择, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-onedrive.png}
  - {name: 微软服务, type: select, proxies: [全球直连, 默认代理, 手动选择, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-microsoft.png}
  - {name: Steam, type: select, proxies: [默认代理, 手动选择, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-steam.png}
  - {name: 游戏平台, type: select, proxies: [全球直连, 默认代理, 手动选择, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-game.png}
  - {name: 测速工具, type: select, proxies: [全球直连, 默认代理, 手动选择, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-speedtest.png}
  - {name: PayPal, type: select, proxies: [默认代理, 手动选择, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-paypal.png}
  - {name: 自定义直连, type: select, proxies: [全球直连, 默认代理, 手动选择, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-direct.png}
  - {name: 漏网之鱼, type: select, proxies: [默认代理, 手动选择, 自动选择, 香港节点, 台湾节点, 新加坡节点, 日本节点, 韩国节点, 美国节点, 加拿大节点, 英国节点, 全球直连], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-fish.png}
  - {name: 香港节点, type: select, include-all: true, filter: "(?i)🇭🇰|香港|(\b(HK|Hong)\b)", icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/region-hk.png}
  - {name: 台湾节点, type: select, include-all: true, filter: "(?i)🇨🇳|🇹🇼|台湾|(\b(TW|Tai|Taiwan)\b)", icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/region-cn.png}
  - {name: 新加坡节点, type: select, include-all: true, filter: "(?i)🇸🇬|新加坡|狮|(\b(SG|Singapore)\b)", icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/region-sg.png}
  - {name: 日本节点, type: select, include-all: true, filter: "(?i)🇯🇵|日本|东京|(\b(JP|Japan)\b)", icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/region-jp.png}
  - {name: 韩国节点, type: select, include-all: true, filter: "(?i)🇰🇷|韩国|首尔|(\b(KR|Korea)\b)", icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/region-kr.png}
  - {name: 美国节点, type: select, include-all: true, filter: "(?i)🇺🇸|美国|洛杉矶|圣何塞|(\b(US|United States)\b)", icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/region-um.png}
  - {name: 加拿大节点, type: select, include-all: true, filter: "(?i)🇨🇦|加拿大|(\b(CA|Canada)\b)", icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/region-ca.png}
  - {name: 英国节点, type: select, include-all: true, filter: "(?i)🇬🇧|英国|伦敦|(\b(UK|United Kingdom|Britain)\b)", icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/region-gb.png}
  - {name: 全球直连, type: select, proxies: [DIRECT], icon: https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/icon/group-global-direct.png}

rules:
  - RULE-SET,custom_direct,全球直连
  - RULE-SET,domain-private,全球直连
  - RULE-SET,ip-private,全球直连,no-resolve
  - RULE-SET,domain-speedtest,测速工具
  - RULE-SET,domain-public-tracker,全球直连
  - RULE-SET,domain-openai,ChatGPT
  - RULE-SET,domain-bing,Copilot
  - RULE-SET,domain-gemini,Gemini
  - RULE-SET,domain-ai-!cn,AI服务
  - RULE-SET,domain-telegram,Telegram
  - RULE-SET,ip-telegram,Telegram,no-resolve
  - RULE-SET,domain-tiktok,TikTok
  - RULE-SET,domain-netflix,Netflix
  - RULE-SET,ip-netflix,Netflix,no-resolve
  - RULE-SET,domain-disney,DisneyPlus
  - RULE-SET,domain-hbo,HBO
  - RULE-SET,domain-primevideo,PrimeVideo
  - RULE-SET,domain-apple-tvplus,AppleTV+
  - RULE-SET,domain-bahamut,Bahamut
  - RULE-SET,domain-spotify,Spotify
  - RULE-SET,domain-emby,Emby
  - RULE-SET,domain-steam@cn,全球直连
  - RULE-SET,domain-games@cn,全球直连
  - RULE-SET,domain-gamedownload,全球直连
  - RULE-SET,domain-steam,Steam
  - RULE-SET,domain-games,游戏平台
  - RULE-SET,domain-github,GitHub
  - RULE-SET,domain-youtube,YouTube
  - RULE-SET,domain-googlefcm,谷歌FCM
  - RULE-SET,domain-google,谷歌服务
  - RULE-SET,ip-google,谷歌服务,no-resolve
  - RULE-SET,domain-apple,苹果服务
  - RULE-SET,ip-apple,苹果服务,no-resolve
  - RULE-SET,domain-onedrive,OneDrive
  - RULE-SET,domain-microsoft,微软服务
  - RULE-SET,domain-communication,即时通讯
  - RULE-SET,domain-social-media-!cn,社交媒体
  - RULE-SET,domain-entertainment,国外媒体
  - RULE-SET,domain-ecommerce,国外电商
  - RULE-SET,domain-paypal,PayPal
  - RULE-SET,domain-geolocation-!cn,默认代理
  - RULE-SET,domain-cn,全球直连
  - RULE-SET,ip-cn,全球直连
  - MATCH,漏网之鱼

rule-anchor:
  ip-mrs: &ip-mrs {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain-mrs: &domain-mrs {type: http, interval: 86400, behavior: domain, format: mrs}
  class-text: &class-text {type: http, interval: 86400, behavior: classical, format: text}
  class-yaml: &class-yaml {type: http, interval: 86400, behavior: classical, format: yaml}

rule-providers: 
  fakeip-filter: {<<: *class-text, url: "https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/fakeip-filter.list"}
  custom_direct: { <<: *class-text, url: "https://raw.githubusercontent.com/baobeibaobei/rule/main/openclash/Custom_Direct.list"}
  domain-private: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  domain-games@cn: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games@cn.mrs"}
  domain-steam@cn: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam@cn.mrs"}
  domain-steam: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.mrs"}
  domain-gamedownload: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-game-platforms-download.mrs"}
  domain-public-tracker: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-public-tracker.mrs" }
  domain-telegram: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs" }
  domain-communication: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-communication.mrs" }
  domain-social-media-!cn: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-social-media-!cn.mrs" }
  domain-openai: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/openai.mrs" }
  domain-bing: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bing.mrs" }
  domain-gemini: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google-gemini.mrs" }
  domain-ai-!cn: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs" }
  domain-github: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
  domain-youtube: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
  domain-apple-tvplus: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-tvplus.mrs"}
  domain-apple: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs"}
  domain-onedrive: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs"}
  domain-microsoft: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  domain-googlefcm: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/googlefcm.mrs"}
  domain-google: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  domain-tiktok: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"}
  domain-netflix: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}
  domain-disney: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/disney.mrs"}
  domain-hbo: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/hbo.mrs"}
  domain-primevideo: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/primevideo.mrs"}
  domain-emby: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-emby.mrs"}
  domain-spotify: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.mrs"}
  domain-bahamut: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bahamut.mrs"}
  domain-games: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games.mrs"}
  domain-entertainment: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-entertainment.mrs"}
  domain-ecommerce: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ecommerce.mrs"}
  domain-paypal: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
  domain-speedtest: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs"}
  domain-geolocation-!cn: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  domain-cn: { <<: *domain-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
  
  ip-private: {<<: *ip-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"}
  ip-cn: { <<: *ip-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  ip-google: { <<: *ip-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  ip-telegram: { <<: *ip-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  ip-netflix: { <<: *ip-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}
  ip-apple: {<<: *ip-mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs"}
